name: ai_20
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  in_app_review: ^2.0.9
  modal_bottom_sheet: ^3.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  syncfusion_flutter_charts: ^28.1.39
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  uuid: ^4.5.1
  cupertino_calendar_picker: ^2.1.3
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  dart_openai: ^5.1.0
  #data base
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  flutter_gen_runner:
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter_gen:
  output: lib/core/gen/
  line_length: 80

flutter_native_splash:
  background_image: assets/images/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
